config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :places

  get '/logout', to: "session#destroy"
  get '/login', to: "session#create"
  resources :access, only: [ :new, :create]
  resources :people, only: [ :new, :index ]

  resources :invitations, only: [ :index ]

  resources :chats, path: "" do
    resources :places do
      post 'vote'
    end
    resource :invitation do
      get 'accept'
      get 'reject'
    end
  end
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  before_save :set_slug
  has_and_belongs_to_many :places
  has_many :invitations
  belongs_to :person
  has_many :votes

  validate :slug, :name, :time, :date, presence: true

  accepts_nested_attributes_for :person

  def to_param
    slug
  end

  def ordered_places
    self.votes.group(:place_id).select("place_id, COUNT(*) as count").map(&:place)
  end

  def votes_for_place(place)
    self.votes.where(place: place).count
  end

  private

  def set_slug
    self.slug = self.name.parameterize

    while Chat.exists?(slug: self.slug)
      self.slug = self.name.parameterize
      self.slug += "-#{random_words.sample}"
    end
  end

  def random_words
    [ "cuddle", "bear", "pug", "kitten", "twinkle", "apple-pie", "baloons", "breeze", "bubbly", "cuddle", "drizzle", "freckles", "glitter", "happy", "honey", "hugs", "jello", "rose", "puppy", "tickle", "yum", "nom", "yummy" ]
  end
end

app/models/chats_places.rb
class ChatsPlaces < ActiveRecord::Base
  belongs_to :chat
  belongs_to :place
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :chat
  belongs_to :person

  validates_uniqueness_of :person, scope: [ :chat ]

  before_create :generate_token

  private

  def generate_token
    self.token = SecureRandom.urlsafe_base64(nil, false)
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :email, presence: true
  has_many :votes
  has_many :invitations

  def to_s
    self.name || self.email
  end

  def with_privacy(on=true)
    on ? "#{self.email.split("@")[0]}@xxxxx" : self.to_s
  end

  def reset_token
    self.token = SecureRandom.urlsafe_base64(nil, false)
    self.token_time = DateTime.now
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_and_belongs_to_many :chats
  has_many :votes

  validates :name, presence: true

  def votes_for_chat(chat)
    votes.where(chat: chat)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates_uniqueness_of :chat, scope: [ :place, :person ]
  belongs_to :chat
  belongs_to :place
  belongs_to :person

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  def new
    @person = Person.new
  end

  def create
    person = Person.find_by_email!(params["person"]["email"])
    AccessMailer.access_request(person).deliver

    redirect_to root_path, notice: "Check your inbox for an access link"
  rescue Exception => e
    puts e.inspect
    redirect_to :back
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login(email)
    session[:person_email] = email
  end

  def current_user
    if session.has_key?(:person_email)
      email = session[:person_email]
      @current_user ||= Person.find_by_email(email)
    end
  rescue ActiveRecord::RecordNotFound
    session[:person_email] = nil
  end

  def logout!
    @current_user = nil
    reset_session
  end

  def email
    current_user.try(:email)
  end

  def logged_in?
    current_user.present?
  end

  def can_access_chat?(chat)
    logged_in? and current_user.invitations.exists?(chat: chat.id)
  end

  helper_method :email, :logged_in?, :can_access_chat?
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
  end

  def new
    @chat = Chat.new
    @chat.person = Person.new
  end

  def create
    @chat = Chat.new(chat_params)

    if logged_in?
      @chat.person = current_user
    else
      @chat.person = Person.where(chat_params[:person_attributes]).first_or_create
    end

    if @chat.save
      login(@chat.person.email)
      @chat.invitations << Invitation.create(person: @chat.person, accepted: true)
      redirect_to chat_path(@chat)
    else
      render 'new'
    end
  end

  def show
    @chat = Chat.find_by_slug(params["id"])

    redirect_to root_path unless @chat

    if logged_in?
      @invitation = current_user.invitations.where(chat: @chat).first
    elsif params[:token]
      @invitation = @chat.invitations.find_by_token(params[:token])
      login(@invitation.person.email)
    end
  rescue
    redirect_to root_path
  end

  private

  def chat_params
    params.require(:chat).permit(:name, :date, :time, person_attributes: [ :email ])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless logged_in?
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def index
    @invitations = current_user.invitations
  end

  def new
    @person = Person.new
  end

  def create
    @chat = Chat.find_by_slug(params[:chat_id])

    emails = params[:person][:email].split(",").map(&:strip)
    emails.each do |email|
      invitee = Person.where(email: email).first_or_create
      invitation = Invitation.new(chat: @chat, person: invitee)

      if invitation.save
        InvitationMailer.to_chat(invitation, @chat, current_user.email).deliver
      end
    end
    redirect_to @chat
  end

  def accept
    @chat = Chat.find_by_slug(params[:chat_id])
    @invitation = current_user.invitations.where(chat: @chat).first
    @invitation.update_attribute(:accepted, true)

    redirect_to @chat
  end

  def reject
    @chat = Chat.find_by_slug(params[:chat_id])
    @invitation = current_user.invitations.where(chat: @chat).first
    @invitation.update_attribute(:accepted, false)

    redirect_to @chat
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def new
    @person = Person.new
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def new
    @chat = Chat.find_by_slug(chat_id)
    @place = Place.new
  end

  def create
    chat_id = params[:chat_id]
    @chat = Chat.find_by_slug(chat_id)
    @place = Place.new(place_params)

    if @place.save
      if @chat
        @chat.places << @place
        redirect_to @chat
      else
        redirect_to @place
      end
    else
      render partial: 'places/new'
    end
  end

  def vote
    @chat = Chat.find_by_slug(chat_id)
    render json: "", status: :forbidden and return unless logged_in? and can_access_chat?(@chat)

    @place = Place.find(place_id)

    chatplace = Vote.where(chat: @chat, person: current_user).first_or_create
    chatplace.update_attribute(:place_id, @place.id)

    render partial: 'chats/places', locals: { chat: @chat }
  end

  private
  def place_params
    params.require(:place).permit(:name, :address)
  end

  def chat_id
    params[:chat_id]
  end

  def place_id
    params[:place_id]
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def destroy
    logout!
    redirect_to root_path
  end

  def create
    person = Person.find_by_token!(params[:token])
    login(person.email)
    redirect_to root_path
  rescue Exception => e
    redirect_to new_access_path, notice: "Invalid token"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def votes_for(place)
    votes = @chat.votes_for_place(place)
    "(#{votes})" if votes
  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/access/new.html.haml
#invitation
  %h1 Send me access email
  = simple_form_for @person, url: :access_index do |f|
    = f.input :email, as: :string, label: false, placeholder: "email"
    = f.submit "Send me access email"

app/views/chats/_places.html.haml
- chat.ordered_places.each do |place|
  %li{ "data-chat-slug" => chat.slug,"data-place-slug" => place.id }
    .details
      %span.place
        =place.name
      %span.votes= votes_for(place)
    %small= place.address
- (chat.places - chat.ordered_places).each do |place|
  %li{ "data-chat-slug" => @chat.slug,"data-place-slug" => place.id }
    .details
      %span.place
        =place.name
      %span.votes= votes_for(place)
    %small= place.address
- if can_access_chat?(@chat)
  %li.suggest
    =link_to "suggest a place", new_chat_place_path(@chat)

app/views/chats/index.html.haml
.content#chat
  =link_to "Create chat", new_chat_path, class: "btn"

app/views/chats/new.html.haml
.content#chat
  = simple_form_for @chat do |f|
    = f.input :name, label: false, placeholder: "what is this nom about?", required: true
    = f.input :date, as: :string, label: false, placeholder: Date.tomorrow.strftime('%d %b, %Y'), required: true
    = f.input :time, as: :string, label: false, placeholder: DateTime.new(2014,6,1,12,30).strftime("%H:%M %P"), required: true
    - unless logged_in?
      = f.simple_fields_for :person do |pe|
        = pe.input :email, as: :string, label: false, placeholder: "your email", required: true

    = f.submit "Create"

app/views/chats/show.html.haml
.container
  .left-column
    #chat
      %h1
        =@chat.name
        %small #{@chat.date.strftime("%a, %d/%m/%Y")} at #{@chat.time.strftime("%H:%M")}

      - if @invitation
        #attending
          - if @invitation.accepted
            = link_to reject_chat_invitation_path(@chat), class: 'attending' do
              I'm going
          - else
            = link_to accept_chat_invitation_path(@chat), class: 'not-attending' do
              I'm not going

      #suggestions
        %h2
          - if @chat.places.any?
            Suggestions
            - if can_access_chat?(@chat)
              %small (click to vote)
          - else
            No suggestions yet
        %ul
          = render partial: 'chats/places', locals: { chat: @chat }

      #team
        %h2 Who is going?
        %ul
          - @chat.invitations.each do |invitation|
            - if invitation.person.email.eql?(email)
              %li{ selected: 'selected'}
                = invitation.person.email
                - if invitation.accepted
                  = fa_icon "check"
                - elsif invitation.accepted.nil?
                  = fa_icon "minus-circle"
                - else
                  = fa_icon "times"
            - else
              %li{ class: (!invitation.accepted.nil? ?  " " : "unconfirmed")}
                = invitation.person.with_privacy(!can_access_chat?(@chat))
                - if invitation.accepted
                  = fa_icon "check"
                - elsif invitation.accepted.nil?
                  = fa_icon "minus-circle"
                - else
                  = fa_icon "times"
          - if can_access_chat?(@chat)
            %li
              =link_to "invite more people", new_chat_invitation_path(@chat)
  .right-column
    #prevelant-location
      .panel
        .location
        #map

app/views/home/index.html.haml
#homepage
  .container
    .left-column
      .panel
        %h1 Nomcensus
        %p
          Lunch choice made easy
        %br
      .demo
        =link_to new_chat_path, class: 'btn' do
          New nomcensus
    .right-column
      .demo
        = image_tag "nomcensus.jpg", class: "demo"
        = image_tag "nomcensus-loggedout.jpg", class: "demo"

app/views/invitations/index.html.haml
#invitations
  .container
    .left-column
      .chat
        =link_to new_chat_path, class: 'btn' do
          New nomcensus
    .right-column
      %h1 Invitations
      %ul
        - if @invitations.any?
          - @invitations.each do |invitation|
            %li{ selected: (!invitation.accepted ? "rejected" : "selected")}
              =link_to invitation.chat do
                = invitation.chat.name
              %small #{invitation.chat.date.strftime("%a, %d/%m/%Y")} at #{invitation.chat.time.strftime("%H:%M")}

app/views/invitations/new.html.haml
#invitation
  %h1 Invite
  = simple_form_for @person, url: :chat_invitation do |f|
    = f.input :email, as: :string, label: false, placeholder: 'email'
    = f.submit "invite"

app/views/layouts/_meta.html.haml
%meta{charset: "utf-8"}
%meta{name: "viewport", content: "width=device-width, initial-scale=1.0" }
%meta{name: "robots", content: "index, follow" }
%meta{property: "fb:admins", content: "622070503" }
%meta{property: "og:type", content: "website" }
%meta{property: "og:locale", content: "en_GB" }
%meta{property: "og:site_name", content: "NomCensus"}
%meta{name: "keywords", content: "nom, nomnom, lunch, chat, decision"}
%meta{property: "og:image", content: "http://nomcensus.com/images/logo.png"}
%meta{ property: "og:url", content: "http://nomcensus.com" }
%meta{property: "og:title", content: "NomCensus"}
%meta{property: "og:description", content: "NomCensus - Lunch choice made easy"}
%meta{ name: "description", content: "NomCensus - Lunch choice made easy"}

app/views/layouts/_navbar.html.haml
.toolbar
  =link_to root_path, class: 'help', title: "Home" do
    =fa_icon "home"
  =link_to "https://github.com/despo/nomcensus", class: 'github', title: "Github" do
    =fa_icon "github"
  =link_to "https://github.com/despo/nomcensus/issues/new", class: 'bugs', title: "Bugs" do
    =fa_icon "bug"
  =link_to "http://twitter.com/despo", class: 'author', title: "@despo" do
    =fa_icon "info-circle"
  - if logged_in?
    =link_to invitations_path, class: 'author', title: "Your Invitations" do
      =fa_icon "bars"
    =link_to logout_path, class: 'author', title: "Logout #{email}" do
      =fa_icon "sign-out"
  - else
    =link_to new_access_path, class: 'author', title: "Login" do
      =fa_icon "sign-in"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: 'layouts/meta' %>
    <title>NomCensus</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render partial: 'layouts/navbar' %>
    <%= yield %>

  </body>
</html>

app/views/places/new.html.haml
.container
  .left-column
    #place
      %h1 Suggest new place

      =simple_form_for [@chat, @place] do |f|
        = f.input :name, label: false, placeholder: "place"
        = f.input :address, label: false, placeholder: "address"
        = f.submit "add", class: "btn"

  .right-column
    #prevelant-location
      .panel
        .location
        #map

app/views/session/new.html.haml
#invitation
  %h1 Send me access email
  = simple_form_for @person, url: :session_index do |f|
    = f.input :email, as: :string, label: false, placeholder: "email"
    = f.submit "Send me access email"